[package]
name = "bldr"
version = "0.1.0"
authors = ["Wil Taylor <cert@wiltaylor.dev>"]
edition = "2018"


[dependencies]
serde = "1.0.105"
serde_derive = "1.0.105"
serde_yaml = "0.8.11"
clap = "2.33.0"
glob = "0.3.0"
